project_id = "geekfgpgzqrdedzwhvei"

[functions.analyze-investment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-workspace-invitation]
verify_jwt = true
